### PR TITLE
Refactoring/filenames

### PR DESCRIPTION
**Pull request by tiinaromu**
Files renamed and organized a bit. #9 is fixed here.

### CODE REVIEW

**Comment by tiinaromu** [comment]
#10 is also partly now fixed - still some duplicate code to refactor but changed common functions to own module.
Also decided to use single quotes. Now there was both.

**Comment by phadej** [comment]
Crap. @ojarva did change everything (?) to double quotes in https://github.com/futurice/meme-booth/commit/e4d91d5542b5362ef9073c69e5c71b160163db5c yet we have `quotmark: single` in `.jshintrc` (double quotes are default in eslint?). I'm no confused which one we want to use.

I could make a config to eslint and jshint and add travis support to run them. Until that let's put this on hold, or you can strip quotmark changing commits for now.

**Comment by ojarva** [comment]
I changed quotes per eslint defaults. I didn't see any reason not to follow defaults, as that's almost always the most sensible way to go.

**Comment by tiinaromu** [comment]
Ok, I'll fix this in another branch. Will close this one now.

**Pull request closed without merging**
